### ISSUE TITLE
Fuel level not decreasing

### ISSUE THREAD

**Issue by eoinmcbennett** [CC-Scripting/CC-Fuel#8]
I am using the old QB-HUD (Before the change) and I have the same issue. Fuel just stays at 100 and never goes down!

__Originally posted by @Duderocktv in https://github.com/CC-Scripting/cc-fuel/issues/6#issuecomment-934017903__

**Comment by Duderocktv** [comment]
No worries! If you need anything from me, let me know!

**Comment by eoinmcbennett** [comment]
> No worries! If you need anything from me, let me know!

If you wouldn't mind answering these few questions

1. Any client errors from cc-fuel?
2. Does the hud fuel indicator update at all e.g does it stay still when you refill or siphon fuel from the car?

**Comment by eoinmcbennett** [comment]
Closed due to inactivity
